### PR TITLE
Adding an initial bit of work towards student cards in Message PopUp

### PR DESCRIPTION
**Pull request by kevinrobinson**
This is adding student cards so that candidates can practice Message PopUp before they take it as a summative assessment.

screen shot 2016-06-16 at 11 00 47 am

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@david-rosales Can you review this?  Gracias!

**Comment by kevinrobinson** [comment]
You can merge this too if you're comfortable with it.  And the Heroku setup will deploy it to http://threeflows.herokuapp.com/ and you can click through to the Message PopUp to verify the changes are deployed!

**Comment by kevinrobinson** [comment]
@david-rosales oh nice, this had some type errors that the build caught! https://travis-ci.org/mit-teaching-systems-lab/threeflows/builds/138109606

Looking at this now, you can do your thing and ignore it.

**Comment by kevinrobinson** [comment]
Pushed a commit working around the problem, so this is passing again!  It looks like the type checker was confused by the `{...student}` expression, or more likely there's something about the way the type checker works that I don't understand well enough yet. :)

**Comment by david-rosales** [comment]
@kevinrobinson Looks good!

**Comment by david-rosales** [comment]
Also, apparently I don't have write access so I can't merge the pull request.

**Comment by kevinrobinson** [comment]
@david-rosales oops, that should be fixed now!

**Comment by david-rosales** [comment]
Ok, I'll merge it now then.

**Pull request merged**
