### PR TITLE
New build process for Teacher Moments using create-react-app

### PR DESCRIPTION
**Pull request by keving17**
This changes the build process for Teacher Moments to use create-react-app which should be more compatible with future build processes for react applications moving forward.

Some things to check still
- [x] does this work with CSV and CSS files?
- [x] what is the deal with #! in url
- [x] merge in testing changes from https://github.com/mit-teaching-systems-lab/threeflows/pull/338

### CODE REVIEW

**Comment by keving17** [comment]
Some notes on the problems so far:

1. `indent`: I also pulled some code from the old ui folder along with that .eslintrc file and everything looks almost identical. the same code that show up in scaffolding_card.jsx both the client and ui folders with the same .eslintrc file has problems in the client folder but not in the ui folder.

2. `react/sort-comp`: I found a react-codemod that is supposed to handle the react/sort-comp problems. These problems came up because of the prop-types codemod I think? However, the codemod doesn't seem to be able to fix the problem.

3. `react/no-unescaped-entities`: This is triggering on mostly apostrophes and other HTML entities. I found that using &apos; to replace the apostrophes fixes the problem but I'm not sure if I should manually go through and replace everything.

4. Finally, the problems in the TeacherMoments.js file are just from me mucking around with the file trying to get it to work. I think the `colon` problems are from the private-threeflows repo not having a linter? I can deal with this file though.

**Comment by kevinrobinson** [comment]
@keving17 Here's some thoughts on your questions, and a few other things I discovered looking at this now.  I've also opened a pull request https://github.com/mit-teaching-systems-lab/threeflows/pull/340 with some progress on this as well.

> indent: I also pulled some code from the old ui folder along with that .eslintrc file and everything looks almost identical. the same code that show up in scaffolding_card.jsx both the client and ui folders with the same .eslintrc file has problems in the client folder but not in the ui folder.

`eslint` can fixup small errors like whitespace problems, just run it with `--fix` or run `yarn lint-quiet` in the client folder which has this config set.  I did this in https://github.com/mit-teaching-systems-lab/threeflows/pull/340.

> react/sort-comp: I found a react-codemod that is supposed to handle the react/sort-comp problems. These problems came up because of the prop-types codemod I think? However, the codemod doesn't seem to be able to fix the problem.

Yeah it seems the codemods we ran changed things in a way that was more complicated than I expected.  One consequence is that the codemod added `props` and `state` instance variables to classes, and this then is different than the sort order that the `react/sort-comp` eslint rule expects. 
 We can just update the lint rule to fix this (allow `props` and `state` first), and I did that in https://github.com/mit-teaching-systems-lab/threeflows/pull/340.

> react/no-unescaped-entities: This is triggering on mostly apostrophes and other HTML entities. I found that using ' to replace the apostrophes fixes the problem but I'm not sure if I should manually go through and replace everything.

To start we can jsut relax the eslint rule to `"react/no-unescaped-entities": ["error", {"forbid": [">", "}"]}],` which excludes the single quote apostrophe from this check.  This is done in https://github.com/mit-teaching-systems-lab/threeflows/pull/340.

> Finally, the problems in the TeacherMoments.js file are just from me mucking around with the file trying to get it to work. I think the colon problems are from the private-threeflows repo not having a linter? I can deal with this file though.

I didn't look at this, but yes if there are linter errors there it's likely because there are actual issues and we didn't have a linter in the older analysis repo.  You should fix these up as part of that work (these should all be simple things like missing semicolons or actual cruft that we want to clean up).

I also discovered a few other things and will comment on them over in https://github.com/mit-teaching-systems-lab/threeflows/pull/340.  Also, I likely won't be able to look at this more this week so feel free to merge in and burn down the remaining bits here.  I can also take another look at any other PRs next week as well.

**Comment by keving17** [comment]
Current status:

- Things seem to generally work.
- 568 flow errors. The "fixed" errors from the previous  618 errors from https://github.com/mit-teaching-systems-lab/threeflows/pull/340 seem to be from deleting the TeacherMoments.js file that was unnecessary for this new build work.

**Comment by keving17** [comment]
yarn test seems to be happy now that flow is gone. Going to go ahead and merge this.
screen shot 2018-03-07 at 4 42 47 pm

**Comment by kevinrobinson** [comment]
@keving17 Yeah!  I think that to ship this you should:

- [ ] verify locally that most pages look good manually
- [ ] run `yarn heroku-postbuild` locally and verify that it compiles files into `ui/build` and doesn't explode
- [ ] deploy!
- [ ] verify in production that pages look good

If you run into problems with the deploy it will prevent you from deploying other code, but it won't bring the site down or do any damage.  So this is reasonably safe to just ship, even if something does goes wrong.  Feel free to @ me on GitHub here if you run into any snags or we could work through them next Wednesday too.

**Comment by keving17** [comment]
Hey @kevinrobinson!

Clarification on how to deploy. I'm not supposed to merge my changes into master yet, right? Do I just do the following commands?
```
$ heroku create
$ git push heroku master
$ heroku open
```
I think I managed to bring the site down just now but things seem to be fixed now with the revert I just did. 

This does seem to work locally so should I just merge this into the feature/authentication branch and start working to get that working locally?

**Comment by keving17** [comment]
Looking through logs now and I'm just generally confused.

From Heroku, it seems that the first deploy I did via command line was deploying code from https://github.com/mit-teaching-systems-lab/threeflows/commit/89f149c5f2e75479885301f9e2fce5d0d998171f. A second deploy was from me merging this branch with master at commit https://github.com/mit-teaching-systems-lab/threeflows/commit/9069ebbccc4dde658fcd8033ba88ca7dd3a9e2fb which I think it triggered an automatic deploy you had set up that watches master. The final deploy using commit https://github.com/mit-teaching-systems-lab/threeflows/commit/a45423b31c1e26327572fe900590a0c52b1a0540 is me reverting my merge into master.
screen shot 2018-03-08 at 3 16 20 pm

Actually looking through the heroku logs, it seems that the new code seemed to work after building https://github.com/mit-teaching-systems-lab/threeflows/commit/9069ebbccc4dde658fcd8033ba88ca7dd3a9e2fb at 19:25 but the crashes and restarts and crashes a bunch of times. Here is the snippet of logs I was looking at. I've attached a txt file of the logs I got after getting threeflows back up at the bottom.
```
2018-03-08T19:28:38.187677+00:00 app[api]: - Release v338 created by user krob@mit.edu
2018-03-08T19:28:38.187677+00:00 app[api]: - Deploy 9069ebbc by user krob@mit.edu
2018-03-08T19:25:58.000000+00:00 app[api]: - Build succeeded
2018-03-08T19:28:39.136179+00:00 heroku[web.1]: - Restarting
2018-03-08T19:28:39.136988+00:00 heroku[web.1]: - State changed from up to starting
2018-03-08T19:28:39Z+00:00 app[deployhooks]: Logplex.rb ran a POST to https://api.rollbar.com/api/1/deploy/?access_token=bb10c72266804eb6b37d9f468b642385&environment=threeflows
2018-03-08T19:28:39.785985+00:00 heroku[web.1]: - Stopping all processes with SIGTERM
2018-03-08T19:28:39.859155+00:00 heroku[web.1]: - Process exited with status 1
2018-03-08T19:28:47.340074+00:00 heroku[web.1]: - Starting process with command `yarn run server`
2018-03-08T19:28:40+00:00 app[heroku-postgres]: - source=DATABASE sample#current_transaction=61351 sample#db_size=80271896bytes sample#tables=7 sample#active-connections=1 sample#waiting-connections=0 sample#index-cache-hit-rate=0.99839 sample#table-cache-hit-rate=0.99996 sample#load-avg-1m=0 sample#load-avg-5m=0 sample#load-avg-15m=0 sample#read-iops=0 sample#write-iops=0.0072917 sample#memory-total=4045008kB sample#memory-free=481480kB sample#memory-cached=2342276kB sample#memory-postgres=13576kB
2018-03-08T19:28:49.872293+00:00 app[web.1]: - yarn run v1.5.1
2018-03-08T19:28:50.094020+00:00 app[web.1]: - $ node server/index.js
2018-03-08T19:28:51.450027+00:00 heroku[web.1]: - State changed from starting to up
2018-03-08T19:28:51.347691+00:00 app[web.1]: - Server is running on port: 35462
2018-03-08T19:28:57.383454+00:00 heroku[router]: - at=info method=POST path="/server/evidence/threeflows/on_response_submitted/3" host=threeflows.herokuapp.com request_id=fc8cf9ba-aa51-44cc-b01a-45c63fafb478 fwd="18.111.106.184" dyno=web.1 connect=1ms service=116ms status=201 bytes=207 protocol=https
2018-03-08T19:28:57.282591+00:00 app[web.1]: - Slack integration not enabled.
2018-03-08T19:28:57.348248+00:00 app[web.1]: - Slack integration not enabled.
2018-03-08T19:28:57.370730+00:00 app[web.1]: - {"command":"INSERT","rowCount":1,"oid":0,"rows":[],"fields":[],"_parsers":[],"RowCtor":null,"rowAsArray":false}
2018-03-08T19:28:57.384392+00:00 app[web.1]: - {"command":"INSERT","rowCount":1,"oid":0,"rows":[],"fields":[],"_parsers":[],"RowCtor":null,"rowAsArray":false}
...
2018-03-08T19:30:44.780791+00:00 app[web.1]: - Slack integration not enabled.
2018-03-08T19:30:44.786007+00:00 app[web.1]: - {"command":"INSERT","rowCount":1,"oid":0,"rows":[],"fields":[],"_parsers":[],"RowCtor":null,"rowAsArray":false}
2018-03-08T19:30:48.328962+00:00 app[web.1]: - /app/ui/build/index.html
2018-03-08T19:30:48.334202+00:00 app[web.1]: - events.js:160
2018-03-08T19:30:48.334205+00:00 app[web.1]: -       throw er; // Unhandled 'error' event
2018-03-08T19:30:48.334206+00:00 app[web.1]: -       ^
2018-03-08T19:30:48.334208+00:00 app[web.1]: - 
2018-03-08T19:30:48.334209+00:00 app[web.1]: - Error: ENOENT: no such file or directory, open '/app/ui/build/index.html'
2018-03-08T19:30:48.334211+00:00 app[web.1]: -     at Error (native)
2018-03-08T19:30:48.348962+00:00 app[web.1]: - error An unexpected error occurred: "Command failed.
2018-03-08T19:30:48.348966+00:00 app[web.1]: - Exit code: 1
2018-03-08T19:30:48.348968+00:00 app[web.1]: - Command: sh
2018-03-08T19:30:48.348969+00:00 app[web.1]: - Arguments: -c node server/index.js
2018-03-08T19:30:48.348983+00:00 app[web.1]: - Directory: /app
2018-03-08T19:30:48.348986+00:00 app[web.1]: - ".
2018-03-08T19:30:48.349243+00:00 app[web.1]: - info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
2018-03-08T19:30:48.349326+00:00 app[web.1]: - info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2018-03-08T19:30:48.348985+00:00 app[web.1]: - Output:
2018-03-08T19:30:48.341416+00:00 heroku[router]: - at=error code=H13 desc="Connection closed without response" method=GET path="/" host=threeflows.herokuapp.com request_id=17cc4b56-97c9-4cd9-9326-e2bbc331c411 fwd="18.111.106.184" dyno=web.1 connect=2ms service=18ms status=503 bytes=0 protocol=https
2018-03-08T19:30:48+00:00 app[postgres.28564]: [meta sequenceId="2676"] [DATABASE] [6-1]  sql_error_code = 08006 LOG:  could not receive data from client: Connection reset by peer
2018-03-08T19:30:48+00:00 app[postgres.28592]: [meta sequenceId="2677"] [DATABASE] [6-1]  sql_error_code = 08006 LOG:  could not receive data from client: Connection reset by peer
2018-03-08T19:30:48.510158+00:00 heroku[web.1]: - State changed from up to crashed
2018-03-08T19:30:48.512553+00:00 heroku[web.1]: - State changed from crashed to starting
2018-03-08T19:30:48.430010+00:00 heroku[web.1]: - Process exited with status 1
2018-03-08T19:30:57.164594+00:00 heroku[web.1]: - Starting process with command `yarn run server`
2018-03-08T19:30:59.753892+00:00 app[web.1]: - yarn run v1.5.1
2018-03-08T19:31:00.004892+00:00 app[web.1]: - $ node server/index.js
2018-03-08T19:31:00.954932+00:00 app[web.1]: - Server is running on port: 49342
2018-03-08T19:31:01.835173+00:00 heroku[web.1]: - State changed from starting to up
```

[Heroku error log.txt](https://github.com/mit-teaching-systems-lab/threeflows/files/1794652/Heroku.error.log.txt)

**Comment by kevinrobinson** [comment]
@keving17 Ah yeah I did not remember that!  I was suggesting that you do try deploying this and it would be pretty safe to do that, but as you found out that was not the case :)  This was a great response, to revert ASAP and bring the site back up, and then dig into what is going on more afterward when things are stable again.

So the error message you awesomely found in the logs is describing the immediate problem:
```
Error: ENOENT: no such file or directory, open '/app/ui/build/index.html'
```
The server code is trying to read the `index.html` file from disk and it doesn't exist in the `ui` folder.  This is because we moved the UI code from `ui/` to `client/` to match Swipe Right, and it's also because the files that create-react-app builds are slightly different than the ones my homegrown build process creates.

This didn't come up locally, because in the current Teacher Moments build process it works mostly the same across local development and production.  But with create-react-app there's a development server to enable things like hot reloading, and we didn't notice that the production setup is different locally until we tried deploying.  But if you run `yarn heroku-postbuild` and then run `yarn server` locally, you'd see this same problem.

I opened https://github.com/mit-teaching-systems-lab/threeflows/pull/345 as a "revert the revert" and then https://github.com/mit-teaching-systems-lab/threeflows/pull/346 can be merged into that, with the fix for the error you ran into in these logs.

@keving17 You can feel free to try this out, and then revert if something else goes wrong, or we can look at this together next week if you want, either is great. 👍

**Pull request merged**
