### PR TITLE
Adds a new git.md instruction file

### PR DESCRIPTION
**Pull request by milsim11**
This adds the new git.md instruction file to master. This instruction file is a quick introduction to using the threeflows repository and pushing commits to master.

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@milsim11 Awesome, this looks great!

To clarify, these are how to work with git and GitHub for any TSL or open source project in general, not just limited to the threeflows repo.

And a nitpicky clarification is that "pushing commits to master" directly is not something we want to do typically.  That would involve taking your local commits and pushing them directly to the master branch on GitHub, without any review process.  The instructions here are for pushing commits on a branch up to GitHub, and then making a pull request to merge those commits into master.

**Comment by kevinrobinson** [comment]
@milsim11 Can you also add a sentence of two "what is this file" at the top of this?  Then this looks great and you can merge this in to master.

**Comment by kevinrobinson** [comment]
@milsim11 Ah sorry!

This looks great, but I was thinking we would add this to the [mit-teaching-systems-lab/docs](https://github.com/mit-teaching-systems-lab/docs) repository.  That's where we have more general-purpose info that applies to any software project in the lab.

Can you close this pull request in the GitHub UI, and open a new pull request with this file over in the docs repository?   Also, it's fine to do that after tomorrow if you're crunched on time, it'll just be helpful for adding the notes we made for future us or future other people. :)

**Comment by milsim11** [comment]
Oh shoot! I'm so sorry, I totally missed that, yeah I'll switch it over

**Comment by kevinrobinson** [comment]
@milsim11 no worries!  this was my mistake as reviewer, I totally missed what repo this was :)  https://github.com/blog/1857-introducing-the-revert-button has the info on reverting if you want to try it out, but there's no harm here and it's fine to put this off for a bit to focus on the playtest stuff first.

**Pull request merged**
