### PR TITLE
Feature/authentication

### PR DESCRIPTION
**Pull request by keving17**
Pulling new data access method into this branch to avoid having to use PRIVATE_SENSITIVE_DATA

### CODE REVIEW

**Comment by keving17** [comment]
I'm going to merge this in for now so I can work on this. I'll merge the authentication branch in again when that piece of work gets done

**Comment by kevinrobinson** [comment]
@keving17 Can you say more about what you're trying to do here?  The description makes it hard to tell the difference between #348 ("Feature/authentication") and this one, #352 ("Feature/authentication").  It also look like this pull request merges commits into `feature/sort-table`:
screen shot 2018-04-02 at 7 50 23 pm

**Comment by keving17** [comment]
Oh right. So this branch `feature/sort-table` was an exploration to use the new material-ui tables that can be easily sorted. We discussed this a bit at issue https://github.com/mit-teaching-systems-lab/threeflows/issues/351.

I was merging in the work I had done at https://github.com/mit-teaching-systems-lab/threeflows/pull/348 into this so I could try working on the table without having to use PRIVATE_SENSITIVE_DATA. I started working on this branch prior to the work at https://github.com/mit-teaching-systems-lab/threeflows/pull/348 and I figured it would be safer to move froward on this branch without PRIVATE_SENSITIVE_DATA.

I actually haven't been able to get this branch working even after this merge because of the old Material UI components breaking so I've been exploring React Virtualized. I'm hoping to push up a new branch today!

**Comment by kevinrobinson** [comment]
@keving17 Got it!  This all makes tons of sense, and a description like this would make a great pull request description :)

**Pull request merged**
